pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
    buildConfiguration: 'Release'

steps:
- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    fileType: 'json'
    targetFiles: '**/appsettings.json'

- script: dotnet test API.UnitTests/API.UnitTests.csproj --logger trx
  displayName: Run unit tests

- script: dotnet test API.IntegrationTests/API.IntegrationTests.csproj --logger trx
  displayName: Run integration tests

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'bulee_resource_connection'
    azureContainerRegistry: '{"loginServer":"buleebanana.azurecr.io", "id" : "/subscriptions/85e88e40-7ca1-48c0-b71d-7f123c16dd9b/resourceGroups/Bulee_Banana/providers/Microsoft.ContainerRegistry/registries/buleebanana"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
    dockerComposeFileArgs: |
        BananaConnection=$(ConnectionStrings.BananaConnectionMssql)
        SendGridAPIKey=$(Keys.SendGridAPI)
        ConfirmationEmailId=$(Keys.ConfirmationEmailId)

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'bulee_resource_connection'
    azureContainerRegistry: '{"loginServer":"buleebanana.azurecr.io", "id" : "/subscriptions/85e88e40-7ca1-48c0-b71d-7f123c16dd9b/resourceGroups/Bulee_Banana/providers/Microsoft.ContainerRegistry/registries/buleebanana"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'
    includeLatestTag: true