pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
    buildConfiguration: 'Release'

steps:
- script: dotnet test API.UnitTests/API.UnitTests.csproj --logger trx
  displayName: Run unit tests

- script: dotnet test API.IntegrationTests/API.IntegrationTests.csproj --logger trx
  displayName: Run integration tests

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    containerRegistry: $(azureContainerRegistry)
    repository: $(repositoryName)
    tags: latest

