pr:
- master

pool:
  vmImage: 'vs2019-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet test API.UnitTests/API.UnitTests.csproj --logger trx
  displayName: Run unit tests

- script: dotnet test API.IntegrationTests/API.IntegrationTests.csproj --logger trx
  displayName: Run integration tests

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: Docker@1
  displayName: Build an image
  inputs:
    command: Build an image
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: bulee_resource_connection
    azureContainerRegistry: $(azureContainerRegistry)
    imageName: $(imageName)
    imageNamesPath: 
    restartPolicy: always

- task: Docker@1
  displayName: Push an image
  inputs:
    command: Push an image
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: bulee_resource_connection
    azureContainerRegistry: $(azureContainerRegistry)
    imageName: $(imageName)
    imageNamesPath: 
    restartPolicy: always
