trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  imageName: 'bulee-banana:$(build.buildNumber)'

steps:
- script: dotnet test API.UnitTests/API.UnitTests.csproj --logger trx
  displayName: Run unit tests

- script: dotnet test API.IntegrationTests/API.IntegrationTests.csproj --logger trx
  displayName: Run integration tests

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: Docker@1
  displayName: Build imageName
  inputs:
    command: Build an image
    containerregistrytype: Container Registry
    dockerHostEndpoint: banana docker registry 
    dockerFile: dockerFile
    imageName: $(imageName)
    imageNamesPath: 
    restartPolicy: always

- task: Docker@1
  displayName: Push Image
  inputs:
    command: Push an image
    containerregistrytype: Container Registry
    dockerHostEndpoint: banana docker registry
    dockerFile: Dockerfile
    imageName: $(imageName)
    imageNamesPath: 
    restartPolicy: always
