pr:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    fileType: 'json'
    targetFiles: '**/appsettings.json'
    
- script: dotnet test API.UnitTests/API.UnitTests.csproj --logger trx
  displayName: Run unit tests

- script: dotnet test API.IntegrationTests/API.IntegrationTests.csproj --logger trx
  displayName: Run integration tests

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    