version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
  
  apiunittests:
    image: ${DOCKER_REGISTRY-}apiunittests
    build:
      context: .
      dockerfile: API.UnitTests/Dockerfile
